# llm/llm_utils.py

import time
import json
from typing import Any, Dict, List, Optional
from openai import AzureOpenAI
from utils import get_env, logger, safe_json_load

# -----------------------------
# Azure OpenAI Clients
# -----------------------------
CHAT_MODEL = get_env("CHAT_MODEL", required=True)
EMBEDDING_MODEL = get_env("EMBEDDING_MODEL", required=True)
IMAGE_MODEL = get_env("IMAGE_MODEL", required=True)

chat_client = AzureOpenAI(
    azure_endpoint=get_env("OPENAI_API_BASE", required=True),
    api_key=get_env("OPENAI_API_KEY", required=True),
    api_version=get_env("OPENAI_API_VERSION", required=True)
)

image_client = AzureOpenAI(
    azure_endpoint=get_env("IMAGE_API_BASE", required=True),
    api_key=get_env("IMAGE_API_KEY", required=True),
    api_version=get_env("OPENAI_API_VERSION", required=True)
)

# -----------------------------
# Helper — retry wrapper
# -----------------------------
def retry(func):
    def wrapper(*args, **kwargs):
        for attempt in range(3):
            try:
                return func(*args, **kwargs)
            except Exception as e:
                logger.warning(f"Retry {attempt+1}/3 failed: {e}")
                time.sleep(1.5)
        logger.error("LLM request failed after 3 retries.")
        raise Exception("LLM failure")
    return wrapper


# -----------------------------
# Chat Completion Wrapper
# -----------------------------
@retry
def chat_completion(
    system_prompt: str,
    user_prompt: str,
    json_mode: bool = False,
    temperature: float = 0.2
) -> str:
    """
    Generic wrapper for Azure OpenAI chat models.
    Returns raw text OR JSON (auto-detected).
    """
    response = chat_client.chat.completions.create(
        model=CHAT_MODEL,
        temperature=temperature,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )

    content = response.choices[0].message["content"]
    if json_mode:
        parsed = safe_json_load(content)
        if parsed is None:
            logger.warning("Expected JSON but got raw text, returning raw.")
        return parsed or content

    return content


# -----------------------------
# Embedding Wrapper
# -----------------------------
@retry
def embed_text(text: str) -> List[float]:
    """Generate Azure OpenAI embeddings."""
    resp = chat_client.embeddings.create(
        model=EMBEDDING_MODEL,
        input=text
    )
    return resp.data[0].embedding


# -----------------------------
# Image Generation Wrapper
# -----------------------------
@retry
def generate_image(prompt: str, size: str = "1024x1024") -> bytes:
    """
    Returns raw image bytes generated by Azure GPT-image-mini.
    """
    response = image_client.images.generate(
        model=IMAGE_MODEL,
        prompt=prompt,
        size=size
    )

    # Azure returns base64 JSON → convert to bytes
    try:
        data = response.data[0].b64_json
        import base64
        return base64.b64decode(data)
    except Exception as e:
        logger.error(f"Image decode failed: {e}")
        return None


# -----------------------------
# JSON-Safe Chat Helper
# -----------------------------
def structured_chat(system_prompt: str, user_prompt: str, schema_name: str):
    """
    Force model to generate a JSON structure reliably.
    """
    full_prompt = (
        f"You MUST respond ONLY in valid JSON.\n"
        f"JSON Schema Name: {schema_name}\n\n"
        f"{user_prompt}"
    )

    result = chat_completion(system_prompt, full_prompt)
    parsed = safe_json_load(result)
    if parsed is None:
        logger.error(f"Failed to parse structured JSON for {schema_name}")
    return parsed or {}
