# pages/3_❓_QnA.py

import os
import json
import streamlit as st
from utils import text_client, get_env, logger
from slide_renderer import extract_slide_structure

st.set_page_config(page_title="3 - Q&A", layout="wide")
st.title("3 — Q&A (Slide-Specific Questions)")

# ------------------------------------------------------------------
# Validate session state
# ------------------------------------------------------------------
selected_slides = st.session_state.get("selected_slide_structs")
if not selected_slides:
    st.error("No slides selected. Please go back and select slides.")
    st.stop()

st.info(
    "Questions below are generated by the LLM after analyzing the **actual slide content**. "
    "Your answers will be used to generate the final PPT."
)

# ------------------------------------------------------------------
# LLM QUESTION GENERATION (STRICT JSON)
# ------------------------------------------------------------------
def generate_questions_for_slide(slide_struct):
    """
    Returns:
      {
        "slide_title": "...",
        "questions": {
            "shape_id": "question text"
        }
      }
    Raises exception if LLM output is invalid
    """

    editable_shapes = slide_struct.get("editable_shapes", [])
    if not editable_shapes:
        raise ValueError("No editable shapes found on slide")

    slide_text_dump = [
        {
            "shape_id": s["shape_id"],
            "text": s["text"]
        }
        for s in editable_shapes
    ]

    system_prompt = (
        "You are an expert presentation consultant.\n"
        "Analyze the slide content and generate meaningful, slide-specific questions.\n\n"
        "RULES:\n"
        "- Generate ONE question per shape_id\n"
        "- Questions must be derived from the slide text\n"
        "- Do NOT ask generic questions\n"
        "- Return ONLY valid JSON\n\n"
        "Required JSON format:\n"
        "{\n"
        '  "slide_title": "<short improved title>",\n'
        '  "questions": {\n'
        '     "shape_id": "question text"\n'
        "  }\n"
        "}"
    )

    user_prompt = json.dumps(
        {
            "slide_preview_text": slide_text_dump
        },
        indent=2
    )

    response = text_client.chat.completions.create(
        model=get_env("CHAT_MODEL", required=True),
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        response_format={"type": "json_object"},  # 🔥 critical
        max_completion_tokens=500
    )

    content = response.choices[0].message.content
    parsed = json.loads(content)

    if "questions" not in parsed or not isinstance(parsed["questions"], dict):
        raise ValueError("Invalid JSON structure from LLM")

    return parsed


# ------------------------------------------------------------------
# Generate questions ONCE per slide (cached)
# ------------------------------------------------------------------
for slide in selected_slides:
    qkey = f"llm_questions_{slide['slide_id']}"
    if qkey not in st.session_state:
        try:
            st.session_state[qkey] = generate_questions_for_slide(slide)
        except Exception as e:
            logger.exception("LLM question generation failed")
            st.session_state[qkey] = {"error": str(e)}

# ------------------------------------------------------------------
# Render UI
# ------------------------------------------------------------------
st.session_state.setdefault("answers_by_slide", {})

for slide in selected_slides:
    slide_id = slide["slide_id"]
    qkey = f"llm_questions_{slide_id}"
    result = st.session_state.get(qkey, {})

    st.markdown("---")
    st.markdown(f"### 📄 Slide: `{slide_id}`")

    # Thumbnail
    if slide.get("png_path") and os.path.exists(slide["png_path"]):
        st.image(slide["png_path"], use_container_width=True)

    if "error" in result:
        st.error(f"LLM question generation failed:\n{result['error']}")
        continue

    slide_title = result.get("slide_title", "Untitled Slide")
    questions = result.get("questions", {})

    st.subheader(f"Proposed Slide Title: {slide_title}")

    st.session_state["answers_by_slide"].setdefault(slide_id, {})

    for shape in slide["editable_shapes"]:
        sid = shape["shape_id"]
        q = questions.get(sid)

        if not q:
            st.warning(f"No question generated for shape {sid}")
            continue

        answer_key = f"ans_{slide_id}_{sid}"
        default_val = st.session_state["answers_by_slide"][slide_id].get(sid, "")

        val = st.text_area(q, value=default_val, key=answer_key)
        st.session_state["answers_by_slide"][slide_id][sid] = val


# ------------------------------------------------------------------
# Navigation
# ------------------------------------------------------------------
col1, col2 = st.columns(2)

with col1:
    if st.button("⬅ Back to Slide Selection"):
        st.switch_page("pages/2_🖼️_Slide_Selection.py")

with col2:
    if st.button("➡ Generate PPT"):
        answers_for_generator = {}

        for slide in selected_slides:
            idx = str(slide["slide_index"])
            answers_for_generator[idx] = st.session_state["answers_by_slide"].get(
                slide["slide_id"], {}
            )

        st.session_state["generation_payload"] = {
            "selected_slides": selected_slides,
            "answers_map": answers_for_generator
        }

        st.switch_page("pages/4_Generate_PPT.py")
